version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - '2501:80'
        volumes:
            - .:/code
            - ./config/docker/nginx/nginx.conf:/etc/nginx/nginx.conf

    php:
        image: php:8.0-fpm
        volumes:
            - .:/code
